#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Solvberget.Droid.Resource", IsApplication=true)]

namespace Solvberget.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int blue_dark = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int blue_light = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int green_dark = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int green_light = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int grey = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int grey_dark = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int grey_light = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int orange_dark = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int orange_light = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int purple_dark = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int purple_light = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int standard_background = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int ui_background = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int ui_black = 2130968588;
			
			// aapt resource value: 0x7f040014
			public const int ui_green = 2130968596;
			
			// aapt resource value: 0x7f04000e
			public const int ui_grey = 2130968590;
			
			// aapt resource value: 0x7f040012
			public const int ui_grey_dark = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int ui_grey_light = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int ui_itembackground = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int ui_itembackground_dark = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int ui_orange = 2130968595;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_card_inverse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawer_shadow_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawer_shadow_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_drawer_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_refresh = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_share = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_star = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int button1 = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int buttonSignIn = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int content_frame = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int drawer_layout = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int editTextPasswordToLogin = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int editTextUserNameToLogin = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int left_drawer = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060017
			public const int menu_refresh = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int menu_share = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int menu_star = 2131099674;
			
			// aapt resource value: 0x7f06000e
			public const int news_ingress = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int news_newstitle = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int news_published = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int progressBar = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int pts_main = 2131099652;
			
			// aapt resource value: 0x7f060018
			public const int search = 2131099672;
			
			// aapt resource value: 0x7f060009
			public const int searchResultsList = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int searchViewPager = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int searchViewPagerTabStrip = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int textView2 = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int textView3 = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int textView4 = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int viewPager = 2131099651;
			
			// aapt resource value: 0x7f060016
			public const int webView = 2131099670;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int item_columns = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_blog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_blogoverview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_blogpost = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_contactinfo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_hourslisting = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_mediadetail = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_newslisting = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fragment_profile = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int fragment_profile_favorites = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int fragment_profile_fines = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int fragment_profile_loans = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int fragment_profile_messages = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int fragment_profile_personalia = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int fragment_profile_reservations = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int fragment_search = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int fragment_searchresults = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int fragment_suggestions_list = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int fragment_suggestions_list_list = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int item_blog = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int item_blogpost = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int item_contactinfobox = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int item_contactperson = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int item_favorite = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int item_fine = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int item_genericfield = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int item_genrestring = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int item_loan = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int item_menu = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int item_message = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int item_news = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int item_openinghour_pair = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int item_openinghours = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int item_reservation = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int item_searchresult = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int item_suggestions_list_summary = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int login = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int mediadetail_audiobook = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int mediadetail_book = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int mediadetail_cd = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int mediadetail_film = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int mediadetail_game = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int mediadetail_journal = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int mediadetail_sheetmusic = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int page_home_view = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int page_webview = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int SplashScreen = 2130903085;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int refresh = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int search_menu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int share = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int star = 2131296259;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int drawer_close = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int drawer_open = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int menu_refresh = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int menu_share = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int menu_star = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int search_title = 2131165191;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MyBaseTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MyTheme = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Theme_Splash = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
