﻿// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Solvberget.Core.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Solvberget.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ServiceUrl_Rating {
            get {
                return ResourceManager.GetString("ServiceUrl_Rating", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Contact {
            get {
                return ResourceManager.GetString("ServiceUrl_Contact", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_BlogPost {
            get {
                return ResourceManager.GetString("ServiceUrl_BlogPost", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_OpeningHours {
            get {
                return ResourceManager.GetString("ServiceUrl_OpeningHours", resourceCulture);
            }
        }
        
        internal static string ServiceUrl {
            get {
                return ResourceManager.GetString("ServiceUrl", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_MediaImage {
            get {
                return ResourceManager.GetString("ServiceUrl_MediaImage", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_News {
            get {
                return ResourceManager.GetString("ServiceUrl_News", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Document {
            get {
                return ResourceManager.GetString("ServiceUrl_Document", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Search {
            get {
                return ResourceManager.GetString("ServiceUrl_Search", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Events {
            get {
                return ResourceManager.GetString("ServiceUrl_Events", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_UserInfo {
            get {
                return ResourceManager.GetString("ServiceUrl_UserInfo", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_BlogListing {
            get {
                return ResourceManager.GetString("ServiceUrl_BlogListing", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_List {
            get {
                return ResourceManager.GetString("ServiceUrl_List", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Lists {
            get {
                return ResourceManager.GetString("ServiceUrl_Lists", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Login {
            get {
                return ResourceManager.GetString("ServiceUrl_Login", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Reservations {
            get {
                return ResourceManager.GetString("ServiceUrl_Reservations", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_BlogDetails {
            get {
                return ResourceManager.GetString("ServiceUrl_BlogDetails", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Favorites {
            get {
                return ResourceManager.GetString("ServiceUrl_Favorites", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Event {
            get {
                return ResourceManager.GetString("ServiceUrl_Event", resourceCulture);
            }
        }
        
        internal static string ServiceUrl_Review {
            get {
                return ResourceManager.GetString("ServiceUrl_Review", resourceCulture);
            }
        }
    }
}
