//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solvberget.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solvberget.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://80.203.160.221:3535/api.
        /// </summary>
        internal static string ServiceUrl {
            get {
                return ResourceManager.GetString("ServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blogs/{0}.
        /// </summary>
        internal static string ServiceUrl_BlogDetails {
            get {
                return ResourceManager.GetString("ServiceUrl_BlogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blogs/.
        /// </summary>
        internal static string ServiceUrl_BlogListing {
            get {
                return ResourceManager.GetString("ServiceUrl_BlogListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blogs/{0}/{1}.
        /// </summary>
        internal static string ServiceUrl_BlogPost {
            get {
                return ResourceManager.GetString("ServiceUrl_BlogPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /info/contact.
        /// </summary>
        internal static string ServiceUrl_Contact {
            get {
                return ResourceManager.GetString("ServiceUrl_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /documents/{0}.
        /// </summary>
        internal static string ServiceUrl_Document {
            get {
                return ResourceManager.GetString("ServiceUrl_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /favorites/.
        /// </summary>
        internal static string ServiceUrl_Favorites {
            get {
                return ResourceManager.GetString("ServiceUrl_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lists/{0}.
        /// </summary>
        internal static string ServiceUrl_List {
            get {
                return ResourceManager.GetString("ServiceUrl_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lists.
        /// </summary>
        internal static string ServiceUrl_Lists {
            get {
                return ResourceManager.GetString("ServiceUrl_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /login.
        /// </summary>
        internal static string ServiceUrl_Login {
            get {
                return ResourceManager.GetString("ServiceUrl_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /documents/{0}/thumbnail.
        /// </summary>
        internal static string ServiceUrl_MediaImage {
            get {
                return ResourceManager.GetString("ServiceUrl_MediaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /news.
        /// </summary>
        internal static string ServiceUrl_News {
            get {
                return ResourceManager.GetString("ServiceUrl_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /info/opening-hours.
        /// </summary>
        internal static string ServiceUrl_OpeningHours {
            get {
                return ResourceManager.GetString("ServiceUrl_OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /documents/{0}/rating.
        /// </summary>
        internal static string ServiceUrl_Rating {
            get {
                return ResourceManager.GetString("ServiceUrl_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /documents/{0}/review.
        /// </summary>
        internal static string ServiceUrl_Review {
            get {
                return ResourceManager.GetString("ServiceUrl_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /documents/search?query={0}.
        /// </summary>
        internal static string ServiceUrl_Search {
            get {
                return ResourceManager.GetString("ServiceUrl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /user/{0}/info.
        /// </summary>
        internal static string ServiceUrl_UserInfo {
            get {
                return ResourceManager.GetString("ServiceUrl_UserInfo", resourceCulture);
            }
        }
    }
}
