//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solvberget.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solvberget.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ServiceUrl {
            get {
                return ResourceManager.GetString("ServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dl.dropboxusercontent.com/u/7343226/solvberget/contact.json.
        /// </summary>
        internal static string ServiceUrl_Contact {
            get {
                return ResourceManager.GetString("ServiceUrl_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dl.dropboxusercontent.com/u/7343226/solvberget/lists/.
        /// </summary>
        internal static string ServiceUrl_List {
            get {
                return ResourceManager.GetString("ServiceUrl_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dl.dropboxusercontent.com/u/7343226/solvberget/lists.json.
        /// </summary>
        internal static string ServiceUrl_Lists {
            get {
                return ResourceManager.GetString("ServiceUrl_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dl.dropboxusercontent.com/u/7343226/solvberget/news.json.
        /// </summary>
        internal static string ServiceUrl_News {
            get {
                return ResourceManager.GetString("ServiceUrl_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dl.dropboxusercontent.com/u/7343226/solvberget/openinghours.json.
        /// </summary>
        internal static string ServiceUrl_OpeningHours {
            get {
                return ResourceManager.GetString("ServiceUrl_OpeningHours", resourceCulture);
            }
        }
    }
}
