//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solvberget.Core.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solvberget.Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Title&quot;: &quot;Supertorsdag: Vaage og Michelet &quot;,
        ///    &quot;Link&quot;: &quot;http://www.stavanger-kulturhus.no/SOELVBERGET/Supertorsdag-Vaage-og-Michelet&quot;,
        ///    &quot;PublishedDateAsDateTime&quot;: {
        ///      &quot;DateTime&quot;: &quot;/Date(1383029400000+0100)/&quot;,
        ///      &quot;UtcDateTime&quot;: &quot;/Date(1383033000000)/&quot;,
        ///      &quot;LocalDateTime&quot;: &quot;/Date(1383033000000+0100)/&quot;,
        ///      &quot;Date&quot;: &quot;/Date(1383001200000+0100)/&quot;,
        ///      &quot;Day&quot;: 29,
        ///      &quot;DayOfWeek&quot;: 2,
        ///      &quot;DayOfYear&quot;: 302,
        ///      &quot;Hour&quot;: 7,
        ///      &quot;Millisecond&quot;: 0,
        ///      &quot;Minute&quot;: 50,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewsSampleJson {
            get {
                return ResourceManager.GetString("NewsSampleJson", resourceCulture);
            }
        }
    }
}
